// Generated by CoffeeScript 1.7.1
(function() {
  var docco, fs, processTemplate, _;

  _ = require('highland');

  processTemplate = require('lodash.template');

  docco = require('./lib/docco');

  fs = require('fs');

  module.exports = function(options) {
    var templateFn, templateStr;
    if (options == null) {
      options = {
        src: "" + __dirname + "/lib/default.template.html"
      };
    }
    templateStr = typeof options === 'object' ? fs.readFileSync(options.src, 'utf-8') : options;
    templateFn = processTemplate(templateStr);
    return _.pipeline(_.map(function(file) {
      file.contents = new Buffer(templateFn(docco(file.path, file.contents.toString())));
      return file;
    }));
  };

}).call(this);
